### ISSUE TITLE
create_batches() from utils.py throws error

### ISSUE THREAD

**Issue by thecerial** [sherjilozair/char-rnn-tensorflow#11]
root@ip-172-31-23-174:/home/ubuntu/char-rnn# python train.py
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
loading preprocessed files
Traceback (most recent call last):
  File "train.py", line 75, in <module>
    main()
  File "train.py", line 39, in main
    train(args)
  File "train.py", line 42, in train
    data_loader = TextLoader(args.data_dir, args.batch_size, args.seq_length)
  File "/home/ubuntu/char-rnn/utils.py", line 22, in __init__
    self.create_batches()
  File "/home/ubuntu/char-rnn/utils.py", line 52, in create_batches
    ydata[-1] = xdata[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by pajowu** [comment]
This happend when self.tensor.size is less than (self.batch_size * self.seq_length). You can avoid that by either reducing sec_lenght or batch_size or increasing the input data.

**Comment by hunkim** [comment]
I put pr #25. Let me know this can solve your issue.

**Comment by hugovk** [comment]
@thecerial PR #25 is merged, can this be closed?

**Comment by hunkim** [comment]
Sure.
