### ISSUE TITLE
KeyError in Sample.py

### ISSUE THREAD

**Issue by lucav31** [sherjilozair/char-rnn-tensorflow#127]
I used the program all the day and it worked great but with my last experiment I got the following error message:

Traceback (most recent call last):
  File "sample.py", line 46, in <module>
    main()
  File "sample.py", line 27, in main
    sample(args)
  File "sample.py", line 43, in sample
    args.sample).encode('utf-8'))
  File "C:\Daten\Programmierung\Python\JokeGenerator\char-rnn-tensorflow-master\char-rnn-tensorflow-master\model.py", line 106, in sample
    x[0, 0] = vocab[char]
KeyError: ' '

Seems like anything is wrong with the arguments, but I haven't changed anything.
BTW, really nice program & fun to use. Thank you.

**Comment by santoshchanveer** [comment]
python --prime (your input )
dont use double quotes for input word
