### ISSUE TITLE
Error while trying to start your software

### ISSUE THREAD

**Issue by thecerial** [sherjilozair/char-rnn-tensorflow#13]
loading preprocessed files
Traceback (most recent call last):
  File "train.py", line 75, in <module>
    main()
  File "train.py", line 39, in main
    train(args)
  File "train.py", line 50, in train
    model = Model(args)
  File "/home/tensorflow/tests/char-lstm-16/model.py", line 53, in __init__
    self.final_state = states[-1]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 126, in _SliceHelper
    raise NotImplementedError("Negative indices are currently unsupported")
NotImplementedError: Negative indices are currently unsupported

**Comment by sherjilozair** [comment]
https://github.com/sherjilozair/char-rnn-tensorflow/pull/12 should have fixed this. Please re-open if this isn't the case.
