### ISSUE TITLE
No validation/test?

### ISSUE THREAD

**Issue by totuta** [sherjilozair/char-rnn-tensorflow#33]
Hi,

Looks like your code doesn't have validation or testing part. Hope it can use some fraction of input.txt for valid/test purpose. Any plan?

**Comment by fujimotomh** [comment]
To anyone interested, [this fork](https://github.com/fujimotomh/char-rnn-tensorflow) has validation and test splitting implemented like Justin Johnson's [torch-rnn](https://github.com/jcjohnson/torch-rnn/blob/master/doc/flags.md#preprocessing) as well as some other things like dropout, state as tuple, and sampling with temperature. I redid many names and the arrangement in the fork, but I hope it's easy to decipher. Also I'd be happy to make a pull request if there's interest.

**Comment by bzz** [comment]
@fujimotomh I might have missed it, but in your branch, where is the code that creates all those files?

```
        vocab_file = os.path.join(self.args.data_dir, "vocab.pkl")
        train_file = os.path.join(args.data_dir, "train.npy")
        val_file = os.path.join(args.data_dir, "val.npy")
        test_file = os.path.join(args.data_dir, "test.npy")
```

**Comment by fujimotomh** [comment]
Hi Alexander. I changed some of the layout of the code from the original
author. I separated the preprocess step from training. The files are
created in preprocess.py.

**Comment by kaihuchen** [comment]
@fujimotomh  
Thanks for making your fork available. I find  the fact that you separated out preprocessing quite useful, since it will allow me to create higher-level "characters"  for discovering more abstract patterns.

I ran some training sessions without problem, but when running sampling (python sample.py --init_from ./checkpoints) I got the following error messages. Wonder if you could give me some input on this problem. Thanks!

<pre>
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.4.0.7 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: GRID K520
major: 3 minor: 0 memoryClockRate (GHz) 0.797
pciBusID 0000:00:03.0
Total memory: 4.00GiB
Free memory: 3.95GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GRID K520, pci bus id: 0000:00:03.0)
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
W tensorflow/core/framework/op_kernel.cc:940] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
Traceback (most recent call last):
  File "sample.py", line 116, in <module>
    ret = setup_and_sample(args)
  File "sample.py", line 93, in setup_and_sample
    saver.restore(sess, checkpoint)
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/training/saver.py", line 1129, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [128,65] rhs shape= [128,128]
         [[Node: save/Assign_22 = Assign[T=DT_FLOAT, _class=["loc:@model/softmax_w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/softmax_w/Adam_1, save/restore_slice_22/_27)]]
Caused by op u'save/Assign_22', defined at:
  File "sample.py", line 116, in <module>
    ret = setup_and_sample(args)
  File "sample.py", line 90, in setup_and_sample
    saver = tf.train.Saver(tf.all_variables())
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/training/saver.py", line 861, in __init__
    restore_sequentially=restore_sequentially)
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/training/saver.py", line 519, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/training/saver.py", line 282, in _AddRestoreOps
    validate_shape=validate_shape))
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ubuntu/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()
</pre>

**Comment by ubergarm** [comment]
@fujimotomh I like how you've cleaned up a lot of the code in your fork. 

It may be possible to pull in some of your work back to this repo.  The easiest might be to just get the `temperature` stuff from `sample.py` back. The other features might take more work now that the forks have diverged. 

Anyway, thanks for sharing!
