### ISSUE TITLE
IndexError is out of Bounce

### ISSUE THREAD

**Issue by thecerial** [sherjilozair/char-rnn-tensorflow#9]
loading preprocessed files
Traceback (most recent call last):
  File "train.py", line 75, in <module>
    main()
  File "train.py", line 39, in main
    train(args)
  File "train.py", line 42, in train
    data_loader = TextLoader(args.data_dir, args.batch_size, args.seq_length)
  File "/home/onetipp/char-rnn/char-rnn-tensorflow/utils.py", line 22, in __init__
    self.create_batches()
  File "/home/onetipp/char-rnn/char-rnn-tensorflow/utils.py", line 52, in create_batches
    ydata[-1] = xdata[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by hunkim** [comment]
Check out pr #25. Your sample size is too small.

**Comment by hugovk** [comment]
@thecerial PR #25 is merged, can this be closed?

**Comment by hunkim** [comment]
Sure.
